import { Suspense } from "react";
import Header from "@/components/layouts/Header";
import { Shell } from "@/components/layouts/Shell";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { AddProductToCartForm } from "@/features/carts";
import { ProductCommentsSection } from "@/features/comments";
import {
  BuyNowButton,
  ProductCard,
  ProductImageShowcase,
  ProductAnalyticsTracker,
} from "@/features/products";
import { AddToWishListButton } from "@/features/wishlists";
import { gql } from "@/gql";
import { getClient } from "@/lib/urql";
import { Metadata } from "next";
import { notFound } from "next/navigation";

type Props = {
  params: {
    slug: string;
  };
};
export const metadata: Metadata = {
  title: `Aesthesionery | Ecommerce Platforum Built with Nextjs 14.`,
  description: "Generated by create next app",
};

const ProductDetailPageQuery = gql(/* GraphQL */ `
  query ProductDetailPageQuery($productSlug: String) {
    productsCollection(filter: { slug: { eq: $productSlug } }) {
      edges {
        node {
          id
          name
          description
          rating
          price
          tags
          totalComments
          sustainability
          ...ProductImageShowcaseFragment
          commentsCollection(first: 5) {
            edges {
              node {
                ...ProductCommentsSectionFragment
              }
            }
          }
          collections {
            id
            label
            slug
          }
        }
      }
    }
    recommendations: productsCollection(first: 4) {
      edges {
        node {
          id
          ...ProductCardFragment
        }
      }
    }
  }
`);

async function ProductDetailPage({ params }: Props) {
  const { data, error } = await getClient().query(ProductDetailPageQuery, {
    productSlug: params.slug as string,
  });

  if (!data || !data.productsCollection || !data.productsCollection.edges)
    return notFound();

  const { id, name, description, price, commentsCollection, totalComments, sustainability } =
    data.productsCollection.edges[0].node;

  // Parse sustainability if it's a string (though it should be an object from GraphQL if typed correctly)
  // In Supabase GraphQL, JSON types are returned as is.
  const impactData = sustainability as {
    materials: string;
    carbonFootprint: string;
    recyclingInstructions: string;
    certifications: string[];
  };

  return (
    <Shell>
      <div className="grid grid-cols-12 gap-x-8">
        <div className="space-y-8 relative col-span-12 md:col-span-7">
          <ProductAnalyticsTracker product={{ id, name, price }} />
          <ProductImageShowcase data={data.productsCollection.edges[0].node} />
        </div>

        <div className="col-span-12 md:col-span-5">
          <section className="flex justify-between items-start max-w-lg">
            <div>
              <h1 className="text-4xl font-semibold tracking-wide mb-3">
                {name}
              </h1>
              <p className="text-2xl font-semibold mb-3">{`$${price}`}</p>
            </div>
            <AddToWishListButton productId={id} />
          </section>

          <section className="flex mb-8 items-end space-x-5">
            <Suspense>
              <AddProductToCartForm productId={id} productName={name} productPrice={price} />
            </Suspense>

            <BuyNowButton productId={id} />
          </section>

          <section>
            <p className="mb-6 text-muted-foreground leading-relaxed">{description}</p>

            <Accordion type="single" collapsible defaultValue="item-1">
              <AccordionItem value="item-1">
                <AccordionTrigger className="text-lg font-medium">Materials & Impact</AccordionTrigger>
                <AccordionContent>
                  <div className="space-y-4 pt-2">
                    {impactData?.materials && (
                      <div>
                        <h4 className="font-semibold text-sm mb-1">Materials</h4>
                        <p className="text-muted-foreground">{impactData.materials}</p>
                      </div>
                    )}

                    {impactData?.carbonFootprint && (
                      <div>
                        <h4 className="font-semibold text-sm mb-1">Carbon Footprint</h4>
                        <p className="text-muted-foreground">{impactData.carbonFootprint}</p>
                      </div>
                    )}

                    {impactData?.recyclingInstructions && (
                      <div>
                        <h4 className="font-semibold text-sm mb-1">End of Life</h4>
                        <p className="text-muted-foreground">{impactData.recyclingInstructions}</p>
                      </div>
                    )}

                    {impactData?.certifications && impactData.certifications.length > 0 && (
                      <div>
                        <h4 className="font-semibold text-sm mb-1">Certifications</h4>
                        <div className="flex flex-wrap gap-2">
                          {impactData.certifications.map((cert, i) => (
                            <span key={i} className="inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-secondary text-secondary-foreground hover:bg-secondary/80">
                              {cert}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </AccordionContent>
              </AccordionItem>
              <AccordionItem value="item-2">
                <AccordionTrigger>Shipping & Returns</AccordionTrigger>
                <AccordionContent>
                  <p className="text-muted-foreground">
                    Spend $80 to receive free shipping for a limited time. Oversized items require additional handling fees.
                    Merchandise can be returned or exchanged within 30 days of delivery.
                  </p>
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </section>
        </div>
      </div>

      <Header heading={`We Think You'll Love`} />

      <div className="container grid grid-cols-2 lg:grid-cols-4 gap-x-8 ">
        {data.recommendations &&
          data.recommendations.edges.map(({ node }) => (
            <ProductCard key={node.id} product={node} />
          ))}
      </div>

      <ProductCommentsSection
        comments={
          commentsCollection
            ? commentsCollection.edges.map(({ node }) => node)
            : []
        }
        totalComments={totalComments}
      />
    </Shell>
  );
}

export default ProductDetailPage;
